[package]
name = "async_basic_example"
version = "0.1.0"
edition = "2021"

[dependencies]
# the runtime 
tokio = { version = "1.0" , features = ["full"] }
# I use the log dependency here to show the time of each exectution in the example
log = "0.4.14" 
simple_logger = "4.0.0" 